// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/randomStrings.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListOfStrings struct {
	//list of string to pass to the encryptor
	List                 []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOfStrings) Reset()         { *m = ListOfStrings{} }
func (m *ListOfStrings) String() string { return proto.CompactTextString(m) }
func (*ListOfStrings) ProtoMessage()    {}
func (*ListOfStrings) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bbaf6140154aa6, []int{0}
}

func (m *ListOfStrings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfStrings.Unmarshal(m, b)
}
func (m *ListOfStrings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfStrings.Marshal(b, m, deterministic)
}
func (m *ListOfStrings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfStrings.Merge(m, src)
}
func (m *ListOfStrings) XXX_Size() int {
	return xxx_messageInfo_ListOfStrings.Size(m)
}
func (m *ListOfStrings) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfStrings.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfStrings proto.InternalMessageInfo

func (m *ListOfStrings) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

//response with encrypted slice of strings
type Response struct {
	List                 []string `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	OneStr               string   `protobuf:"bytes,2,opt,name=oneStr,proto3" json:"oneStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_30bbaf6140154aa6, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *Response) GetOneStr() string {
	if m != nil {
		return m.OneStr
	}
	return ""
}

func init() {
	proto.RegisterType((*ListOfStrings)(nil), "encryptor_service.listOfStrings")
	proto.RegisterType((*Response)(nil), "encryptor_service.Response")
}

func init() {
	proto.RegisterFile("proto/randomStrings.proto", fileDescriptor_30bbaf6140154aa6)
}

var fileDescriptor_30bbaf6140154aa6 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x4a, 0xcc, 0x4b, 0xc9, 0xcf, 0x0d, 0x2e, 0x29, 0xca, 0xcc, 0x4b, 0x2f, 0xd6,
	0x03, 0x8b, 0x09, 0x09, 0xa6, 0xe6, 0x25, 0x17, 0x55, 0x16, 0x94, 0xe4, 0x17, 0xc5, 0x17, 0xa7,
	0x16, 0x95, 0x65, 0x26, 0xa7, 0x2a, 0x29, 0x73, 0xf1, 0xe6, 0x64, 0x16, 0x97, 0xf8, 0xa7, 0x41,
	0x55, 0x0a, 0x09, 0x71, 0xb1, 0x80, 0x04, 0x24, 0x18, 0x15, 0x98, 0x35, 0x38, 0x83, 0xc0, 0x6c,
	0x25, 0x33, 0x2e, 0x8e, 0xa0, 0xd4, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x6c, 0xf2, 0x42, 0x62,
	0x5c, 0x6c, 0xf9, 0x79, 0xa9, 0xc1, 0x25, 0x45, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50,
	0x9e, 0x51, 0x32, 0x17, 0x5f, 0x31, 0xc4, 0xd8, 0x60, 0x88, 0x75, 0x42, 0x81, 0x5c, 0x02, 0xee,
	0xa9, 0x25, 0xc1, 0x19, 0x89, 0x46, 0xa6, 0x66, 0x30, 0x1b, 0x15, 0xf4, 0x30, 0x9c, 0xa5, 0x87,
	0xe2, 0x26, 0x29, 0x69, 0x2c, 0x2a, 0x60, 0x0e, 0x72, 0xd2, 0x88, 0x52, 0x4b, 0xad, 0x48, 0xcc,
	0x8d, 0x87, 0x2b, 0xd1, 0x87, 0xb3, 0x74, 0xa1, 0x8a, 0xf5, 0xc1, 0xde, 0x4f, 0x62, 0x03, 0x53,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x94, 0x16, 0x85, 0x5a, 0x22, 0x01, 0x00, 0x00,
}
