// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// StringsServiceClient is the client API for StringsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StringsServiceClient interface {
	GetSha256Strings(ctx context.Context, in *ListOfStrings, opts ...grpc.CallOption) (*Response, error)
}

type stringsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStringsServiceClient(cc grpc.ClientConnInterface) StringsServiceClient {
	return &stringsServiceClient{cc}
}

func (c *stringsServiceClient) GetSha256Strings(ctx context.Context, in *ListOfStrings, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/encryptor_service.stringsService/GetSha256Strings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StringsServiceServer is the server API for StringsService service.
// All implementations must embed UnimplementedStringsServiceServer
// for forward compatibility
type StringsServiceServer interface {
	GetSha256Strings(context.Context, *ListOfStrings) (*Response, error)
	mustEmbedUnimplementedStringsServiceServer()
}

// UnimplementedStringsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStringsServiceServer struct {
}

func (UnimplementedStringsServiceServer) GetSha256Strings(context.Context, *ListOfStrings) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSha256Strings not implemented")
}
func (UnimplementedStringsServiceServer) mustEmbedUnimplementedStringsServiceServer() {}

// UnsafeStringsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StringsServiceServer will
// result in compilation errors.
type UnsafeStringsServiceServer interface {
	mustEmbedUnimplementedStringsServiceServer()
}

func RegisterStringsServiceServer(s grpc.ServiceRegistrar, srv StringsServiceServer) {
	s.RegisterService(&_StringsService_serviceDesc, srv)
}

func _StringsService_GetSha256Strings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOfStrings)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StringsServiceServer).GetSha256Strings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/encryptor_service.stringsService/GetSha256Strings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StringsServiceServer).GetSha256Strings(ctx, req.(*ListOfStrings))
	}
	return interceptor(ctx, in, info, handler)
}

var _StringsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "encryptor_service.stringsService",
	HandlerType: (*StringsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSha256Strings",
			Handler:    _StringsService_GetSha256Strings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/randomStrings.proto",
}
