version: '3.5'

services:
  encryptor-service:
    build: ./encryptor-service
    ports:
    - 9000:23455
    environment:
      service_adress: "9000"

  randomizer-service:
    build: ./randomizer-service
    ports:
    - 9000:23456
    environment:
      service_adress: "9001"
   # depends_on:
     # - encryptor-service