version: '3.5'

services:
  encryptor-service:
    ports:
    - 9000:9000
    env_file:
      - services-ev.env
    build:
      ./encryptor-service

  randomizer-service:
    ports:
    - 9000:9001
    env_file:
      - services-ev.env
    build:
      ./randomizer-service
    depends_on:
      - encryptor-service